version: "3"

services:
    node:
        container_name: nodeapp
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: mongonode
        image: mongo
        ports:
            - "27018:27017"
        logging:
            driver: none
